### ISSUE TITLE
Gitに上げる際に起きている問題

### ISSUE THREAD

**Issue by myonT** [myonT/L4S#4]

**Comment by myonT** [comment]
@ryosebach 

開発上の問題ではないのですがなぜか今日になってGitにあげられなくなってしましました。
どうやらcommit（？）まではできているようで何度かやったせいか２個コミットするものが溜まってるよ、のように表示されています
エラーを調べるとSSHキー？の設定しなおしをしろとのことでした
また登録をしなおすということでしょうか？


<img width="562" alt="2017-10-05 2 34 39" src="https://user-images.githubusercontent.com/26405404/31190464-201c0f42-a976-11e7-9c7b-7ec85a1f9cbf.png">

**Comment by ryosebach** [comment]
@myonT 
ssh-add -A
って打ってみてー

**Comment by myonT** [comment]
@ryosebach 
ありがとうございます！あがりました
初回の時に聞いたssh gitHubをうっておくということみたいなことですかね…？

**Comment by ryosebach** [comment]
そうだねぇ...ちょっと確認してみる
ターミナルを起動しなおしたら，一旦 `ssh-add -A` を打ってからgitを使う感じで対処してみてー
